### PR TITLE
Main Implementation: Timers

### PR DESCRIPTION
**Pull request by YSJL**
Implemented timers and other tweaks in GUI

### CODE REVIEW

**Comment by YSJL** [comment]
We still need to decide whether to implement the "start" button
and how we are going to use the recorded score and show the "leaderboard"

**Comment by gosbhs12** [comment]
I think we can do making the leaderboard and showing the recorded time later. For the start button, we can just make the main screen for the game. Also, we can do it later.

**Comment by gosbhs12** [comment]
Overall, looks good!
Thank you for your last touch!

**Comment by dnjsxor999** [comment]
Great to see the actual timer on the memory game.
Thank you for your last touch!

**Pull request merged**
