### PR TITLE
Pop-up Menu Button Added

### PR DESCRIPTION
**Pull request by schae44**
I add a pop-up menu button in the memory game layout

### CODE REVIEW

**Comment by gosbhs12** [comment]
Good job! but why is the LogicGame2048 imported into the MemoryGame class? does it the reason why we use the same format of popup from the Logicgame?

**Comment by gosbhs12** [comment]
If does, I think we should revise the popup's name, not like pop_up_2048.
I mean we use it commonly in different games.

**Comment by dnjsxor999** [comment]
great!

**Comment by YSJL** [comment]
Other than what Jisan said, looks great to me!
I think the "problem" is from using the popup_2048.xml.
Maybe import that directly and we can change the name of popup_2048?

**Comment by schae44** [comment]
> If does, I think we should revise the popup's name, not like pop_up_2048. I mean we use it commonly in different games.

Yes, I agree with the idea that we change the name of the file more generally and reuse it for both games.
I will fix it soon and thanks for correcting it :)

**Comment by YSJL** [comment]
I'll merge for now to maintain continuity for the next pull request!

**Pull request merged**
