### PR TITLE
Gomoku: Properly Implemented Coordinate System

### PR DESCRIPTION
**Pull request by YSJL**
JaeGotNae

### CODE REVIEW

**Comment by gosbhs12** [comment]
Nice work!!

**Comment by dnjsxor999** [comment]
Great!! the concise method here!

**Comment by schae44** [comment]
Awesome!! Thanks for your time and effort in fixing the screen ratio problem!

**Comment by schae44** [comment]
Make sure to delete the terminal print statement in the code if it is unnecessary :)

**Comment by gosbhs12** [comment]
I will do it

**Pull request merged**
